# Generated by Django 5.1.7 on 2025-05-14 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_contrat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('etat', models.CharField(choices=[('effectué', 'Effectué'), ('remboursé', 'Remboursé')], max_length=20)),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detail', models.TextField()),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.paiement')),
            ],
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raison', models.TextField()),
                ('date_remboursement', models.DateField(auto_now_add=True)),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.paiement')),
            ],
        ),
    ]
