# Generated by Django 5.1.7 on 2025-05-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_paiement_facture_remboursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='objet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
