# Generated by Django 5.1.7 on 2025-05-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_objet_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo_profil',
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
