# Generated by Django 5.1.7 on 2025-05-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='images/default_jZulbUq.webp', upload_to='images/'),
        ),
    ]
