# Generated by Django 5.1.7 on 2025-05-20 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='photo_profil',
        ),
    ]
