# Generated by Django 5.1.7 on 2025-05-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_photo_profile_photo_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo_profil',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
